config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  
  devise_scope :user do
    authenticated :user do
      root to: 'categories#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users#home', as: :unauthenticated_root
    end
  end

  resources :categories, only: %i[index new create destroy] do
    resources :items, only: %i[index new create destroy] do
      resources :item_categories, only: %i[create destroy]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :icon
  belongs_to :user
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories, dependent: :destroy
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories
  validates :name, :user_id, presence: true
  validates :amount, numericality: true
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
  has_many :categories, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_user

  # GET /categories or /categories.json
  def index
    @categories = @user.categories
    @item_categories = ItemCategory.all
    @items = @user.items
    update_total_amount
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @items = []
    @category.item_categories.order(:id).each do |item_category|
      @items << item_category.item_categories
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = @user
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

   # DELETE /category/1 or /category/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    update_total_amount

    respond_to do |format|
      format.html { redirect_to category_path, notice: 'Category was successfully destroyed!' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end

  # def delete_item_amount
  #   @items = @user.items
  #   @total = @items.map { |item| item.amount }.sum
  #   if 

  # end

  def update_total_amount
    @items = @user.items
    @total = @items.map { |item| item.amount }.sum
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_user

  # GET /items or /items.json
  def index
    @categories = Category.find_by(id: params[:category_id])
    @items = ItemCategory.includes(:item).where(category: @categories).order(created_at: :desc)
    @total = @items.map { |paid| paid.item.amount }.sum
  end

  # GET /items/new
  def new
    @categories = @user.categories
    @category = @categories.find(params[:category_id])
    @item = Item.new
  end

  def create
    @category = Category.find(params[:category_id])
    @item = @user.items.new(item_params)

    return unless @item.save

    @item_categories = ItemCategory.new(category_id: @category.id, item_id: @item.id)
    return unless @item_categories.save

    redirect_to category_items_path(@category)
  end
  # ====================================================
  # POST /items or /items.json
  # def create
  #  @category = Category.find(params[:category_id])
  # @item = @category.items.build(item_params)
  # @item_categories = ItemCategory.new(category_id: @category.id, item_id: @item.id)

  # if @item.save
  #  @item_categories = ItemCategory.create(category_id: @category.id, item_id: @item.id)
  # redirect_to categories_path
  # end

  # @item_categories = ItemCategory.new(category_id: @category.id, item_id: @item.id)
  # if @item_categories.save

  # redirect_to categories_path
  # end
  # end
  # ===============================================

  # DELETE /items/1 or /items/1.json
  def destroy
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to category_items_path, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def home
    @user = current_user
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="nav category-head">
  <div class="actions login-btn">
    <%#= f.submit "SAVE", class: 'login-btn' %>
  </div>
  <h2 class="nav-head category-head">CATEGORIES</h2>
  <div class="actions login-link">
      <% if user_signed_in? %>
        <%= button_to 'LOGOUT', destroy_user_session_path, method: :delete, class: "login-btn" %>
      <% end %>
    </div>
</div> 

<div class="total-div">  TOTAL BUDGET: <span class="total"><strong>$<%= sprintf('%.2f', @total) %></strong></span></div>

<div class="categories-div">
  <% @categories.each do |category| %>
    <div class="categories-each">
    <% if category.icon.attached? %>
      <div class="icon">
        <img src="<%= (url_for(category.icon)) %>", alt="shopping_image", style="widt:60p; heigh:60p;", class="icon-image">
      </div>
      <span class="category-name"><%= link_to category.name.upcase, category_items_path(category.id) %></span>
    
      <div>
        <% total = 0 %>
          <% @item_categories.each do |expense| %>
            <% if expense.category_id == category.id %>
              <% total += expense.item.amount %>
           <% end %>
           <% end %>
            <span class="category-amount">$<%= sprintf('%.2f', total) %></span> 
        <% end %>
      </div>

      <% if total.zero? %>
      <div>
        <%= button_to "Delete #{category.name}", category_path(category), method: :delete, class: 'delete-btn' %>
      </div>
      <% end %>
    </div>
    <% end %>
</div>

<%= button_to "ADD CATEGORY", new_category_path, method: :get, class: "btn cat-btn" %>

app/views/categories/new.html.erb
<div class="nav">
  <div class="actions login-link">
    <%= link_to "Back",  authenticated_root_path, method: :get, class: 'login-link' %>
  </div>
  <h2 class="nav-head">ADD CATEGORY</h2>
</div>

<%= form_with model: @category, url: categories_path, local: true do |f| %>
<div>
  <%= f.text_field :name, placeholder: 'Category name', class: 'input' %>
</div>
<div>
  <%= f.file_field :icon %>
</div>
<div>
  <%= f.submit "SAVE", class: 'btn cat-btn' %>
</div>

<% end %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<div class="nav">
  <div class="actions login-link">
    <%= link_to "Back", '/', method: :get, class: 'login-link' %>
  </div>
    <h2 class="nav-head">ITEMS</h2>
  <div class="actions login-btn">
      <%#= f.submit "SAVE", class: 'login-btn' %>
  </div>
</div>


  <div class="total-div"><%= @categories.name.upcase %>  TOTAL AMOUNT: <span class="total"><strong>$<%= sprintf('%.2f', @total) %></strong></span></div>


<% @items.each do |item| %>

<div class="items">
<div class="flex">
  <p  class="item"><%= item.item.name %><span class="total">$<%= sprintf('%.2f', item.item.amount) %><span/><%= button_to "Delete #{item.item.name}", category_item_path(item.category, item), method: :delete, class: 'delete-btn' %></p>
</div>
</div>
<% end %>

<%= button_to "ADD ITEM", new_category_item_path(params[:category_id]), method: :get, class: "btn cat-btn" %>

app/views/items/new.html.erb
<div class="nav">
  <div class="actions login-link">
    <%= link_to "Back", category_items_path, method: :get, class: 'login-link' %>
  </div>
  <h2 class="nav-head">ADD ITEM</h2>
  <div class="actions login-btn">
      <%#= f.submit "SAVE", class: 'login-btn' %>
    </div>
</div>

<%= form_with model: @item, url: category_items_path do |f| %>
  <p></p><%= @category.name%> category:</p>
<div>
  <%= f.text_field :name, placeholder: 'Item name', class: 'input' %>
</div>
<div>
  <%= f.number_field :amount, step: '0.01', placeholder: 'Amount', class: 'input' %>
</div>
  <%#= f.collection_select :category_id, Category.where(user_id: current_user.id), :id, :name, { prompt: "Select category" } %>

<div>
  <%= f.submit "SAVE",  class: 'btn cat-btn' %>
</div>

<% end %>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/home.html.erb
<div class="home">
  <div class="logo">
    <p><span class="i-logo">i</span>Budget</p>
  </div>

  <div class="home-btns">
    <%= button_to "LOG IN", new_user_session_path, method: :get, class: "btn" %>
    <%= button_to "SIGN UP", new_user_registration_path, method: :get, class: "btn" %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <h1><%= @user.name %></h1>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>